title: Fabian Visser
logo: /assets/imgPhoto from Fabian.jpg
description: Welcome to my page! This will contain projects I find worth sharing
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
